# Generated by Django 4.0 on 2021-12-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types_Of_Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('releasedate', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Types_Of_Games',
                'verbose_name_plural': 'Types_Of_Gamess',
            },
        ),
    ]
