# Generated by Django 4.0 on 2021-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_of_games',
            name='releasedate',
            field=models.CharField(max_length=30),
        ),
    ]
